---
affinity: {}
dhcpEnabled: false
domain: ""
env:
#  - name: VIRTUAL_HOST
#    value: <nameOverride>.<domain>
  - name: TZ
    value: Europe/Berlin
fullnameOverride: ""
imageTag: latest
nameOverride: pihole
nodeSelector: {}
podAnnotations: {}
storageClassName: ""
storageSizeRequest: 1Gi
tlsEnabled: true
tolerations: []
