---
{{- with $.Values }}
{{- if .tlsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ include "fullname" $ }}
data:
{{ ($.Files.Glob "tls.*").AsSecrets | indent 2 }}
type: kubernetes.io/tls
{{- end }}
{{- end }}
