---
{{- with $.Values }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ include "fullname" $ }}-tcp
spec:
  ports:
    - name: dns
      port: 53
      protocol: TCP
      targetPort: dns-tcp
  selector:
    {{- include "selectorLabels" $ | nindent 4 }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ include "fullname" $ }}-udp
spec:
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: dns-udp
    {{- if .dhcpEnabled }}
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: dhcp
    {{- end }}
  selector:
    {{- include "selectorLabels" $ | nindent 4 }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ include "fullname" $ }}-web
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    {{- if .tlsEnabled }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    {{- end }}
  selector:
    {{- include "selectorLabels" $ | nindent 4 }}
{{- end }}
